### ISSUE TITLE
Collector key_labels template incorrect

### ISSUE THREAD

**Issue by alimli** [lrk/ansible-role-prometheus-sql-exporter#4]
I am using SQL Exporter version 0.5. 
I had to change the in collector_file.yml.j2 as following in order to sql exporter start.

key_labels: [{{ metric.key_labels | default([]) | join(',')}}]

**Comment by lrk** [comment]
@alimli thank you for the feedback.
Could you submit a PR with your fix ?
Thank you.

**Comment by lrk** [comment]
TY
